package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListPetsParams creates a new ListPetsParams object
// with the default values initialized.
func NewListPetsParams() *ListPetsParams {

	return &ListPetsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListPetsParamsWithTimeout creates a new ListPetsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListPetsParamsWithTimeout(timeout time.Duration) *ListPetsParams {

	return &ListPetsParams{

		timeout: timeout,
	}
}

// NewListPetsParamsWithContext creates a new ListPetsParams object
// with the default values initialized, and the ability to set a context for a request
func NewListPetsParamsWithContext(ctx context.Context) *ListPetsParams {

	return &ListPetsParams{

		Context: ctx,
	}
}

// NewListPetsParamsWithHTTPClient creates a new ListPetsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListPetsParamsWithHTTPClient(client *http.Client) *ListPetsParams {

	return &ListPetsParams{
		HTTPClient: client,
	}
}

/*ListPetsParams contains all the parameters to send to the API endpoint
for the list pets operation typically these are written to a http.Request
*/
type ListPetsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list pets params
func (o *ListPetsParams) WithTimeout(timeout time.Duration) *ListPetsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list pets params
func (o *ListPetsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list pets params
func (o *ListPetsParams) WithContext(ctx context.Context) *ListPetsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list pets params
func (o *ListPetsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list pets params
func (o *ListPetsParams) WithHTTPClient(client *http.Client) *ListPetsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list pets params
func (o *ListPetsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ListPetsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
