package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new operations API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for operations API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
ListPets lists pets filtered by some parameters

This will show all available pets by default.
You can get the pets that are out of stock
*/
func (a *Client) ListPets(params *ListPetsParams, authInfo runtime.ClientAuthInfoWriter) (*ListPetsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListPetsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "listPets",
		Method:             "GET",
		PathPattern:        "/pets",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ListPetsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*ListPetsOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
